// Copyright (c) The Bitcoin Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or https://opensource.org/license/mit.

#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H

/**
 * DNS seeds for TeslaChain networks.
 * Each entry is a pair of (hostname, supports_onion).
 * Format: {host, false} — host string + whether supports Tor onion.
 *
 * These are placeholder/development seeds. Real DNS seed infrastructure
 * needs to be deployed when TeslaChain has public nodes.
 *
 * For regtest: no DNS seeds (local-only network, connects to 127.0.0.1)
 */

struct DNSSeed {
    const char* name;
    bool supports_onion;
};

/** Mainnet DNS seeds (placeholder — no real TeslaChain DNS seeds yet) */
static const DNSSeed mainnetDNSSeeds[] = {
    // Placeholder: replace with real TeslaChain DNS seeds when available
    // Example: {"seed.teslachain.invalid.", false},
};

/** Testnet DNS seeds (placeholder — no real TeslaChain DNS seeds yet) */
static const DNSSeed testnetDNSSeeds[] = {
    // Placeholder: replace with real TeslaChain testnet DNS seeds when available
    // Example: {"seed.testnet.teslachain.invalid.", false},
};

/** Testnet4 DNS seeds (placeholder) */
static const DNSSeed testnet4DNSSeeds[] = {
};

/** Signet DNS seeds (placeholder) */
static const DNSSeed signetDNSSeeds[] = {
};

/**
 * List of fixed seed nodes for TeslaChain networks.
 * Format: BIP155 serialized (networkID, addr, port) tuples.
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Currently empty for TeslaChain since it's an isolated network.
 * Populate with real seed nodes when available.
 */

/** Mainnet fixed seeds — empty for isolated TeslaChain */
static const uint8_t chainparams_seed_main[] = {
};

/** Testnet fixed seeds — empty for isolated TeslaChain */
static const uint8_t chainparams_seed_test[] = {
    0x00  // Placeholder: zero-length arrays not valid in C++, keep one byte
};

/** Testnet4 fixed seeds — empty for isolated TeslaChain */
static const uint8_t chainparams_seed_testnet4[] = {
    0x00  // Placeholder: zero-length arrays not valid in C++, keep one byte
};

/** Signet fixed seeds — empty for isolated TeslaChain */
static const uint8_t chainparams_seed_signet[] = {
    0x00  // Placeholder: zero-length arrays not valid in C++, keep one byte
};

#endif // BITCOIN_CHAINPARAMSSEEDS_H
